# i. Introduction

========================================================================================================

Milestones 2

Nama : Farras Annisa

Batch : HCK-027

This program is designed to create an inference model based on the trained model.

========================================================================================================

# ii. Import Libraries

In [7]:
# Import libraries
import pickle
import pandas as pd

# Read Model

In [8]:
with open('model.pkl', 'rb') as file:
    ModelInf = pickle.load(file)

# Input Data

In [9]:
Client1 = {
    'Age': 25,
    'Gender': 'Female',
    'Technology_Usage_Hours': 8.0,
    'Social_Media_Usage_Hours': 3,
    'Gaming_Hours': 0.1,
    'Screen_Time_Hours': 6.0,
    'Stress_Level': 'High',
    'Sleep_Hours': 9.0,
    'Physical_Activity_Hours': 0.5,
    'Support_Systems_Access': 'Yes',
    'Work_Environment_Impact': 'Neutral',
    'Online_Support_Usage': 'Yes'
}

Client1 = pd.DataFrame([Client1])
Client1

,Age,Gender,Technology_Usage_Hours,Social_Media_Usage_Hours,Gaming_Hours,Screen_Time_Hours,Stress_Level,Sleep_Hours,Physical_Activity_Hours,Support_Systems_Access,Work_Environment_Impact,Online_Support_Usage
0,25,Female,8.0,3,0.1,6.0,High,9.0,0.5,Yes,Neutral,Yes

In [10]:
Client2 = {
    'Age': 37,
    'Gender': 'Male',
    'Technology_Usage_Hours': 10,
    'Social_Media_Usage_Hours': 3,
    'Gaming_Hours': 6,
    'Screen_Time_Hours': 11,
    'Stress_Level': 'Low',
    'Sleep_Hours': 1,
    'Physical_Activity_Hours': 3,
    'Support_Systems_Access': 'Yes',
    'Work_Environment_Impact': 'Negative',
    'Online_Support_Usage': 'No'
}

Client2 = pd.DataFrame([Client2])
Client2

,Age,Gender,Technology_Usage_Hours,Social_Media_Usage_Hours,Gaming_Hours,Screen_Time_Hours,Stress_Level,Sleep_Hours,Physical_Activity_Hours,Support_Systems_Access,Work_Environment_Impact,Online_Support_Usage
0,37,Male,10,3,6,11,Low,1,3,Yes,Negative,No

# Prediction Results

In [ ]:
# Patient 1 Prediction
PredClient1 = ModelInf.predict(Client1)
print(PredClient1)

[2]

In [12]:
# Patient 2 Prediction
PredClient2 = ModelInf.predict(Client2)
print(PredClient2)

[3]